# Generated by Django 4.0.2 on 2022-02-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromeuser',
            name='sentiment',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
